// Game Contants
const LIVES_DEFAULT = "LIVES: III";
const LIVES_THREE = "LIVES: III";
const LIVES_TWO = "LIVES: II";
const LIVES_ONE = "LIVES: I";
const LIVES_INFINITY = "LIVES: ∞";

const DIFFICULTY_DEFAULT = "EASY";
const DIFFICULTY_HARD = "HARD";
const DIFFICULTY_MEDIUM = "MEDIUM";
const DIFFICULTY_EASY = "EASY";


const GAME_MODE_DEFAULT = "CLASSIC";
const GAME_MODE_CLASSIC = "CLASSIC";
const GAME_MODE_CLOCK = "CLOCK RACE";

export {
    LIVES_DEFAULT,
    LIVES_THREE,
    LIVES_TWO,
    LIVES_ONE,
    LIVES_INFINITY,
    DIFFICULTY_DEFAULT,
    DIFFICULTY_HARD,
    DIFFICULTY_MEDIUM,
    DIFFICULTY_EASY,
    GAME_MODE_DEFAULT,
    GAME_MODE_CLASSIC,
    GAME_MODE_CLOCK
}